import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import DataTable from 'datatables.net-react';
// import DT from 'datatables.net-dt';
// import DataTablesCore from 'datatables.net-dt';
// import 'datatables.net-staterestore-dt';
// import $ from "jquery";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="mt-0"
      >
        {children}
      </body>
    </html>
  );
}
